<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>PDDL</string>
	<key>fileTypes</key>
	<array>
		<string>pddl</string>
	</array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#meta</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#scalars</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#time-qualifiers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#parameters</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#unexpected</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>meta</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.pre-parsing</string>
            <key>match</key>
            <string>^;;\s*!pre-parsing:\s*{\s*type:\s*"(command|nunjucks|jinja2|python)"\s*,\s*(command:\s*"([\w:\-/\\\. ]+)"\s*(,\s*args:\s*\[([^\]]*)\])?|data:\s*"([\w:\-/\\\. ]+)")\s*}</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.pre-parsing.type</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.pre-parsing.command</string>
              </dict>
              <key>5</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>begin</key>
                    <string>"</string>
                    <key>end</key>
                    <string>"</string>
                    <key>name</key>
                    <string>variable.parameter.pre-parsing.data</string>
                  </dict>
                </array>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.pre-parsing.data</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.preprocessor</string>
            <key>match</key>
            <string>^;;\s*!</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.template.flow-control</string>
            <key>match</key>
            <string>{%[^%]+%}</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.template.literal</string>
            <key>match</key>
            <string>{{[^}]+}}</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.pddl.header</string>
            <key>match</key>
            <string>\b(define|domain|problem)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.pddl.requirements</string>
            <key>match</key>
            <string>:(strips|typing|negative-preconditions|disjunctive-preconditions|equality|existential-preconditions|universal-preconditions|quantified-preconditions|conditional-effects|fluents|numeric-fluents|object-fluents|adl|durative-actions|duration-inequalities|continuous-effects|derived-predicates|derived-functions|timed-initial-literals|timed-effects|preferences|constraints|action-costs|timed-initial-fluents|time|supply-demand)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.pddl.global</string>
            <key>match</key>
            <string>:(requirements|types|constants|predicates|functions|derived|action|durative-action|event|process|domain|objects|init|goal|metric|extends|timeless|axiom)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.pddl.action</string>
            <key>match</key>
            <string>:(parameters|precondition|effect)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.pddl.action.durative</string>
            <key>match</key>
            <string>:(parameters|duration|condition|effect)\b</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line</string>
            <key>match</key>
            <string>;.*$</string>
          </dict>
        </array>
      </dict>
      <key>scalars</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric</string>
            <key>match</key>
            <string>\b[-+]?([0-9]*\.[0-9]+|[0-9]+)\b</string>
          </dict>
        </array>
      </dict>
      <key>time-qualifiers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.other.pddl_qualifier</string>
            <key>match</key>
            <string>\b(at start|at end|over all)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.delta_t</string>
            <key>match</key>
            <string>#t\b</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.logical</string>
            <key>match</key>
            <string>\b(and|not|or|either)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.numeric</string>
            <key>match</key>
            <string>(&gt;|&lt;|&gt;=|&lt;=|=|/|\*|\+)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.effects</string>
            <key>match</key>
            <string>\b(assign|increase|decrease|forall|exists)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.undefined</string>
            <key>match</key>
            <string>\b(undefined)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.metric</string>
            <key>match</key>
            <string>\b(minimize|maximize)\b</string>
          </dict>
        </array>
      </dict>
      <key>parameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
            <key>match</key>
            <string>\?\w+\b</string>
          </dict>
        </array>
      </dict>
      <key>unexpected</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>invalid.illegal</string>
            <key>match</key>
            <string>:[\w-]+\b</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.pddl</string>
    <key>uuid</key>
    <string>956B19CF-953A-4E2A-9813-9EC5626CC12E</string>
  </dict>
</plist>